# Generated by Django 5.1.7 on 2025-03-14 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True)),
                ('service_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('can_access_articles', models.BooleanField(default=False)),
            ],
        ),
    ]
