# Generated by Django 5.1 on 2024-08-27 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('cnt', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Anome Categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('original_title_japanese', models.CharField(max_length=255)),
                ('banner_image', models.ImageField(upload_to='images/anime_banners/')),
                ('cover_image', models.ImageField(upload_to='images/anime_covers/')),
                ('short_description', models.TextField()),
                ('description', models.TextField()),
                ('type', models.CharField(max_length=100)),
                ('studio', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
                ('status', models.CharField(max_length=100)),
                ('theme', models.CharField(max_length=100)),
                ('rating', models.FloatField(default=0)),
                ('rating_count', models.PositiveIntegerField(default=0)),
                ('duration', models.PositiveIntegerField()),
                ('quality', models.CharField(max_length=100)),
                ('views', models.PositiveIntegerField(default=0)),
                ('genre', models.ManyToManyField(related_name='animes', to='anime.animecategory')),
            ],
            options={
                'verbose_name_plural': 'Anime Series',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='AnimeRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField()),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='anime.anime')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Anime Ratings',
                'ordering': ('anime',),
                'unique_together': {('anime', 'user')},
            },
        ),
    ]
