# Generated by Django 5.1 on 2024-08-28 17:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0002_anime_add_time_animerating_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='views',
        ),
        migrations.CreateModel(
            name='AnimeViewCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views', models.PositiveIntegerField(default=0)),
                ('daily_views', models.PositiveIntegerField(default=0)),
                ('weekly_views', models.PositiveIntegerField(default=0)),
                ('monthly_views', models.PositiveIntegerField(default=0)),
                ('yearly_views', models.PositiveIntegerField(default=0)),
                ('last_day_updated', models.DateField(default=django.utils.timezone.now)),
                ('last_week_updated', models.DateField(default=django.utils.timezone.now)),
                ('last_month_updated', models.DateField(default=django.utils.timezone.now)),
                ('last_year_updated', models.DateField(default=django.utils.timezone.now)),
                ('anime', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='view_count', to='anime.anime')),
            ],
        ),
    ]
