# Generated by Django 5.1 on 2024-08-28 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0003_remove_anime_views_animeviewcount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animeviewcount',
            options={'ordering': ('anime',), 'verbose_name_plural': 'Anime View Counts'},
        ),
    ]
