# Generated by Django 5.1 on 2024-08-28 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0004_alter_animeviewcount_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animecategory',
            options={'ordering': ('name',), 'verbose_name_plural': 'Anime Categories'},
        ),
    ]
