# Generated by Django 5.1 on 2024-08-30 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0007_animetheme_remove_anime_theme_anime_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animecategory',
            name='cnt',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='animecategory',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='animetheme',
            name='cnt',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='animetheme',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название темы'),
        ),
    ]
