# Generated by Django 5.1 on 2024-08-31 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0009_animecomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='comment_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
