# Generated by Django 5.1 on 2024-09-01 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0011_animeepisode'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='available_episodes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
