"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-p)4pt*l!w4_a(8)*v#bttp##+y!86&bws6cezmu)6q%r_yre&h'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # myapps
    'articles',
    'users',
    'externalAPIs',
    
    # other
    'rest_framework',
    'drf_spectacular',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# DRF
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'externalAPIs.authentication.ApiKeyAuthentication'
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

AUTH_USER_MODEL = 'users.User'

SIMPLE_JWT = {
    # Время жизни токенов
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=5),           # Время жизни access-токена (по умолчанию 5 минут)
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),             # Время жизни refresh-токена (по умолчанию 1 день)
    'ROTATE_REFRESH_TOKENS': False,                           # Если True, при обновлении токена выдается новый refresh-токен
    'BLACKLIST_AFTER_ROTATION': False,                       # Если True, старые refresh-токены добавляются в черный список после ротации
    'UPDATE_LAST_LOGIN': True,                               # Если True, обновляет поле last_login у пользователя при получении токена

    # Алгоритмы и ключи
    'ALGORITHM': 'HS256',                                    # Алгоритм подписи токена (HS256, HS384, HS512, RS256 и др.)
    'SIGNING_KEY': SECRET_KEY,                               # Секретный ключ для подписи (по умолчанию берется из SECRET_KEY Django)
    'VERIFYING_KEY': SECRET_KEY,                                   # Ключ для проверки подписи (нужен для асимметричных алгоритмов, например, RS256)
    'AUTH_HEADER_TYPES': ('Bearer',),                        # Типы заголовков аутентификации (например, 'Bearer', 'JWT')
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',                # Имя заголовка, в котором передается токен

    # Поля и данные в токене
    'USER_ID_FIELD': 'id',                                   # Поле модели пользователя, используемое как идентификатор в токене
    'USER_ID_CLAIM': 'user_id',                              # Название поля в payload токена для идентификатора пользователя
    'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',  # Правило проверки пользователя

    # Настройки токенов
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),  # Классы токенов для аутентификации
    'TOKEN_TYPE_CLAIM': 'token_type',                        # Название поля в payload, указывающего тип токена (access или refresh)
    'JTI_CLAIM': 'jti',                                      # Название поля для уникального идентификатора токена (JWT ID)
    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',        # Название поля для времени истечения sliding-токена
    'SLIDING_TOKEN_LIFETIME': timedelta(minutes=5),          # Время жизни sliding-токена (если используется)
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=1),     # Время жизни refresh для sliding-токена

    # Черный список токенов (опционально, требует настройки)
    'TOKEN_OBTAIN_SERIALIZER': 'rest_framework_simplejwt.serializers.TokenObtainPairSerializer',  # Сериализатор для получения пары токенов
    'TOKEN_REFRESH_SERIALIZER': 'rest_framework_simplejwt.serializers.TokenRefreshSerializer',    # Сериализатор для обновления токенов
    'TOKEN_VERIFY_SERIALIZER': 'rest_framework_simplejwt.serializers.TokenVerifySerializer',      # Сериализатор для проверки токенов
    'TOKEN_BLACKLIST_SERIALIZER': 'rest_framework_simplejwt.serializers.TokenBlacklistSerializer', # Сериализатор для черного списка

    # Дополнительные настройки
    'TOKEN_USER_CLASS': 'rest_framework_simplejwt.models.TokenUser',  # Класс пользователя для токенов
    'AUDIENCE': None,                                        # Поле audience (aud) в токене (опционально)
    'ISSUER': None,                                          # Поле issuer (iss) в токене (опционально)
    'LEEWAY': 0,                                             # Допустимое отклонение времени для проверки истечения токена (в секундах)
}

PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.Argon2PasswordHasher',  # Argon2
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',  # PBKDF2 как запасной
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
]

